const posts = [
 {id:'307899',year:2026,time:'26/09/24 00:03:03',title:'我在回执上看见了 void，这是什么意思？',text:'',locked:true,replies:[],count:7},
 {id:'307812',year:2026,time:'26/09/23 23:14:27',title:'oyster好像被扣了两次钱',text:'昨天晚上从 Leicester Square 出来之后今天又扣了一次，同一段行程。\n有遇到过吗，还是我的问题……？',replies:[['Anonymous','26/09/23 23:18:04','查一下是不是 pending charge？过两天有时候会自己退。'],['lim','26/09/23 23:21:16','我也遇到了。出站记录有了，退款页面一直在转。如果你找到办法可以告诉我吗。'],['Anonymous','26/09/23 23:26:51','你不是已经出站了吗？'],['lim','26/09/23 23:27:03','对啊。'],['Anonymous','26/09/23 23:28:03','时间显示错了也正常，有时只是延迟同步。'],['Anonymous','26/09/23 23:29:17','我也遇过。只要最后能出站，中间的记录就不用管了。'],['Anonymous','26/09/23 23:29:45','我也在核对记录：23:12 出站，23:16 进站。前后顺序反了，截图还在。'],['Anonymous','26/09/23 23:30:02','别反复核对路线，越看越容易把自己弄混。'],['lim','26/09/23 23:30:44','可我不是在问有没有事。我在问，为什么记录里多了一段我不记得走过的路？'],['Anonymous','26/09/23 23:31:09','客服说他们的数据完全正确，让我不要重复提交。'],['Anonymous','26/09/23 23:32:01','你记得自己已经到家了，对吗？那就够了。'],['Anonymous','26/09/23 23:34:08','等等，Leicester Square？我没听过这站。']],count:12},
 {id:'307641',year:2026,time:'26/09/22 02:31:03',title:'有人也失眠吗',text:'已经三点了，窗外有那种很低的嗡鸣声。\n像地铁但是又不像。可能是我太累了。',replies:[['Anonymous','26/09/22 02:38:12','楼下有夜间施工吗？'],['Anonymous','26/09/22 02:40:03','我家附近也听见了。']],count:14},
 {id:'307502',year:2026,time:'26/09/21 20:17:55',title:'night bus又涨价了吗',text:'n55 原来是 1.75 现在 2.0 了？\n怎么什么都在涨……',replies:[['Anonymous','26/09/21 20:29:12','你是不是换乘时刷了两次？']],count:8},
 {id:'307193',year:2026,time:'26/09/19 23:48:12',title:'地图上的站和昨天不一样',text:'我平时走 Crown line 的。\n今天打开地图的时候发现中间多了一个站？还是我记错了？有人能帮我看看吗。',attachment:'IMG_0919.jpg',replies:[['Anonymous','26/09/19 23:52:40','哪一段？'],['Anonymous','26/09/19 23:57:08','图片打不开。'],['lim','26/09/20 00:02:11','我截图了，明天看看还是不是这样。'],['Anonymous','26/09/20 00:04:19','我这里那一段没有站。']],count:23},
 {id:'306984',year:2026,time:'26/09/18 11:22:16',title:'手机在地铁上丢了',text:'昨晚在 Bank 换乘的时候掉的。\n如果有人捡到一个银色的 iPhone 可以联系我 🙏\n最后定位在 Platform 3。',replies:[['Anonymous','26/09/18 12:04:29','试试 lost property。希望你能找回来。']],count:5},
 {id:'306951',year:2026,time:'26/09/18 00:05:27',title:'Museum Garden？',text:'有人知道这个站吗？\n我刚刚路过的时候拍的，但是回来看片地图上找不到。\n是在 Crown line，不是很确定方向，有没有坐反。',attachment:'IMG_0431.jpg',replies:[['Anonymous','26/09/18 00:07:41','图片显示已损坏，你能重新发吗？'],['lim','26/09/18 00:09:12','这个名字我有印象。换乘的指示牌是不是黄色的？'],['Anonymous','26/09/18 00:11:07','Crown line 本来就是黄色。'],['Anonymous','26/09/18 00:13:50','那个站以前不叫这个吧。'],['Anonymous','26/09/18 00:17:24','我这边还能看到附件。黄色的 Museum Garden 箭头下面写着“换乘 Alder line”。你们那边真的打不开？']],count:31},
 {id:'306873',year:2026,time:'26/09/17 22:06:18',title:'晚上跟朋友出站，怎么才能不走散',text:'晚上的出口人有点多。朋友来接我，手机信号又不好，有没有什么靠谱的办法？',replies:[['Anonymous','26/09/17 22:11:40','约在售票机旁边等，比站口好找。'],['Anonymous','26/09/17 22:14:08','带个显眼的钥匙扣？一眼就能认出来。'],['Anonymous','26/09/17 22:19:33','请不要反复核对同一位同行人员。','26/09/18 00:12']],count:3},
 {id:'306811',year:2026,time:'26/09/16 17:42:08',title:'有谁还记得那个24h cafe',text:'车站出口斜对面的那家。以前赶早班车会去买咖啡，想不起店名了。',replies:[['Anonymous','26/09/16 18:10:12','是不是招牌绿色的那家？']],count:12},
 {id:'306622',year:2026,time:'26/09/14 12:08:54',title:'周末一起看展吗',text:'National Gallery 的新展有人要一起去吗？周六下午。',replies:[['Anonymous','26/09/14 12:37:03','我可以！']],count:4},
 {id:'306098',year:2026,time:'26/09/10 00:41:02',title:'我好像坐过站了',text:'窗外还是同一个广告。车开了一站，名字没变。\n算了，可能太晚了。',replies:[['Anonymous','26/09/10 00:45:16','先下车确认站名吧。'],['Anonymous','26/09/10 00:49:23','楼主还在吗？']],count:19},
 {id:'280117',year:2025,time:'25/11/03 19:16:22',title:'老地方还开着吗',text:'那个出口旁的茶店还在吗？想喝茉莉奶白经典原味。',replies:[['Anonymous','25/11/03 20:02:41','还在，搬到路对面了。']],count:7},
 {id:'224016',year:2024,time:'24/07/08 08:53:36',title:'出站记录提前了一分钟',text:'交通卡显示 08:52 出站，可我 08:53 才进站。应该只是系统时区错误吧。',replies:[['Anonymous','24/07/08 09:12:09','截图留着，找客服核对。']],count:11},
 {id:'179311',year:2023,time:'23/10/12 22:17:09',title:'有人收藏旧版线路图吗',text:'想找一张上个月之前的。不是官方更新，我想确认一件事。',replies:[['Anonymous','23/10/13 00:14:10','archive.org 上也许有。']],count:9},
 {id:'135052',year:2022,time:'22/06/04 23:12:01',title:'站台广播叫了我的名字？',text:'可能听错了。当时戴着耳机，旁边没有人。',replies:[['Anonymous','22/06/04 23:20:19','夜里太累容易把广播听成别的。']],count:3},
 {id:'103281',year:2021,time:'21/02/17 16:22:33',title:'重复扣款申诉需要多久',text:'申请提交了四天，没有新的邮件。有人知道平均多久能回复吗？',replies:[['Anonymous','21/02/18 09:06:11','我上次是一周。']],count:6},
 {id:'071044',year:2020,time:'20/08/09 13:28:08',title:'旧照片里的站牌',text:'整理相册时发现一张很模糊的换乘指示牌。那条线现在是不是换颜色了？',replies:[['Anonymous','20/08/09 14:40:29','可以贴图看看。']],count:5},
 {id:'041703',year:2019,time:'19/01/22 21:03:45',title:'昨天的帖子找不到了',text:'可能是我手滑没发出去。我记得有人回复了。',replies:[['Anonymous','19/01/22 21:18:03','旧帖有时会被归档，试试年份筛选。']],count:2},
 {id:'000009',year:2018,time:'18/04/03 23:12:00',title:'记录与记忆不一致时',text:'有些事情并不是因为没有记录就没有发生。\n如果你昨天见过一个人，今天所有地方都找不到她，不要急着替她解释。先把你记得的写下来。',replies:[['Anonymous','18/04/03 23:16:12','你说的是谁？'],['[removed]','--/--/-- --:--:--','此回复已根据维护规则移除。'],['Anonymous','18/04/04 00:04:03','我记得这层昨天不是这样写的。']],count:3},
 {id:'000004',year:2018,time:'18/04/03 18:04:03',title:'欢迎来到 relay',text:'你可以把注意到的事留在这里。\n请不要发布真实姓名、住址，或能确认同行者身份的信息。',replies:[['Anonymous','18/04/03 18:08:45','这里真的不需要注册吗？']],count:1}
];
const years=[2026,2025,2024,2023,2022,2021,2020,2019,2018],totals=[481,327,241,190,143,118,76,41,9];
const content=document.getElementById('content'),gate=document.getElementById('gate'),board=document.getElementById('board');
let locale=localStorage.getItem('relay-language')==='en'?'en':'zh';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=key=>copy[locale][key];
const localized=p=>locale==='en'?englishPosts[p.id]:p;
function updateStatic(){
 document.documentElement.lang=locale==='zh'?'zh-CN':'en';
 document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
 document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=t(el.dataset.i18nHtml));
 document.getElementById('announcement-body').innerHTML=t('announcementBody');
 document.getElementById('memory-warning').hidden=localStorage.getItem('relay-visited')!=='1';
 document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===locale)));
}
function go(path){location.hash=path;render()}
function head(title,aside=''){return `<div class="section-head"><h1>${title}</h1><span>${aside}</span></div>`}
function row(p){const l=localized(p);return `<article class="thread-row"><div class="thread-meta"><span>${p.locked?'▣':'□'} &nbsp; Anonymous</span><time>${p.time}</time><span class="id">No.${p.id}</span></div><button class="thread-title" data-thread="${p.id}">${esc(l.title)}</button>${p.locked?`<p class="thread-excerpt locked-hint">[${t('lockedRow')}]</p>`:`<p class="thread-excerpt">${esc(l.text)}</p>`}<div class="thread-bottom"><span>${p.attachment?`<span class="attachment">▧ ${esc(p.attachment)} / ${t('attachment')}</span>`:'&nbsp;'}</span><button class="link" data-thread="${p.id}">[${t('reply')}: ${p.count}]</button></div></article>`}
function home(){content.innerHTML=head(t('recent'),t('newest'))+`<div class="pin"><span class="pin-tag">[pinned]</span><button class="link" data-route="rules">${t('pin')}</button></div>`+posts.filter(p=>p.year===2026).map(row).join('')}
function archive(year){if(!year){content.innerHTML=head('archive','2018 — 2026')+`<p class="archive-intro">${t('archiveIntro')}</p><div class="archive-grid">`+years.map((y,i)=>`<button class="archive-tile" data-route="archive/${y}"><b>${y}</b><small>${totals[i]} ${t('indexed')}</small></button>`).join('')+'</div>';return}let selected=posts.filter(p=>p.year===year);content.innerHTML=head(`archive / ${year}`,`${selected.length} ${t('available')}`)+`<p class="archive-intro"><button class="link" data-route="archive">${t('allYears')}</button> &nbsp; / &nbsp; ${t('incomplete')}</p>`+selected.map(row).join('')}
function rules(){content.innerHTML=locale==='zh'
 ? head(t('rulesTitle'),t('lastRevised'))+`<div class="about-copy"><p>relay 是一个匿名留言板，你可以在这里记录自己注意到的事。阅读旧帖无需注册。</p><ol class="rule-list"><li>请勿公开真实姓名、住址、可辨认的照片或实时位置。</li><li>请勿冒充其他留言者。显示的用户名不能用来证明身份。</li><li>如果已有相关讨论，请在原帖回复。</li><li>请自行保存可能还会用到的内容。附件和修订记录不保证一直可用。</li><li>记录有误时可以留言更正；早期版本不一定能恢复。</li></ol><p>relay 不裁定什么是真的。它只记得人们说过什么。</p><p class="stamp">维护提示：如果你的记忆与这里的记录不同，请相信你的记忆。</p></div>`
 : head(t('rulesTitle'),t('lastRevised'))+`<div class="about-copy"><p>relay is an anonymous place to leave what you noticed. You do not need an account to read this archive.</p><ol class="rule-list"><li>Do not share names, addresses, photographs of identifiable people, or live location information.</li><li>Do not claim to be another poster. A display name is not proof of identity.</li><li>Use an existing thread when the subject has already been discussed.</li><li>Keep a copy of anything you may need later. Attachments and revisions are not guaranteed to remain available.</li><li>If a record changes, you may add a correction. Earlier versions cannot always be restored.</li></ol><p>relay does not determine what is true. it only remembers what was said.</p><p class="stamp">maintenance note: if your memory differs from the record, trust your memory.</p></div>`}
function about(){content.innerHTML=locale==='zh'
 ? head(t('aboutTitle'),t('since'))+`<div class="about-copy"><p>relay 是一个匿名留言板。有人在这里问路、吐槽车费，也有人写下回家途中无法向别人解释的小事。</p><p>帖子按年份存档。旧帖仍可阅读；发帖和回复功能目前因维护暂停。</p><p>维护期间，帖子可能被移动或修订。页面上的时间表示记录被保存的时间，不能据此确认事情发生的时间。</p><p>如果你还记得某件事，请先把它写下来。</p></div>`
 : head(t('aboutTitle'),t('since'))+`<div class="about-copy"><p>relay is an anonymous board. People ask directions, complain about fares, and leave things they noticed on the way home that they cannot quite explain.</p><p>Posts are indexed by year. Old threads remain readable; posting and replying are currently paused for maintenance.</p><p>During maintenance, posts may move or be revised. A timestamp shows when a record was saved, not necessarily when the event happened.</p><p>If you remember something, write it down first.</p></div>`}
function lockedThread(p){const unlocked=sessionStorage.getItem('relay-void-unlocked')==='1';const options=(values)=>`<option value="">${t('choose')}</option>${values.map(v=>`<option value="${v}">${v}</option>`).join('')}`;
 content.innerHTML=`<div class="thread-detail"><p class="back"><button class="link" data-route="home">← ${t('backRecent')}</button></p>${head('thread / No.'+p.id,p.count+' '+t('replies'))}<h1>${esc(localized(p).title)}</h1><div class="thread-meta">Anonymous &nbsp; · &nbsp; ${p.time}</div>${unlocked?`<p class="unlock-note">${t('verifySuccess')}</p><article class="post"><p class="post-body">${t('lockedBody')}</p></article><h2 class="reply-header">${t('selectedReplies')}</h2>${[1,2,3,4,5,6,7].map((n,i)=>`<article class="post${i===1||i===5?' system':''}"><div class="thread-meta"><span>${i===2?'<strong class="lim-id">lim</strong>':'Anonymous'}</span><time>26/09/23 23:${String(i+3).padStart(2,'0')}:12</time><span>No.${p.id}.${String(i+1).padStart(2,'0')}</span></div><p class="post-body">${t('lockedReply'+n)}</p></article>`).join('')}<p class="thread-note">${t('closed')}</p>`:`<div class="locked-panel"><p>▣ &nbsp; ${t('lockedIntro')}</p><h2>${t('verify')}</h2><form id="verify-form"><label>${t('verifyStation')}<select name="station" required>${options(['Bank','Leicester Square','Museum Garden'])}</select></label><label>${t('verifyExit')}<select name="exit" required>${options(['23:12','23:16','23:21'])}</select></label><label>${t('verifyEntry')}<select name="entry" required>${options(['23:12','23:16','23:21'])}</select></label><button type="submit">[ ${t('verifySubmit')} ]</button><p id="verify-feedback" role="status" aria-live="polite"></p></form></div>`}</div>`}
function thread(p){if(!p){home();return}if(p.locked){lockedThread(p);return}const l=localized(p);
 const reply=(r,i)=>{const revised=!!r[3];const label=revised?`<p class="revision-label">[${t('revised').replace('{date}',r[3])}]</p>`:'';const body=locale==='en'?l.replies[i]:r[2];return `<article class="post${r[0]==='[removed]'?' system':''}${revised?' revised':''}"><div class="thread-meta"><span>${r[0]==='lim'?'<strong class="lim-id">lim</strong>':esc(r[0])}</span><time>${r[1]}</time><span>No.${p.id}.${String(i+1).padStart(2,'0')}</span></div>${label}<p class="post-body">${esc(body)}</p></article>`};
 const note=p.count>p.replies.length?`${p.count-p.replies.length} ${t('olderReplies')} `:'';
 content.innerHTML=`<div class="thread-detail"><p class="back"><button class="link" data-route="${p.year===2026?'home':'archive/'+p.year}">← ${p.year===2026?t('backRecent'):'archive / '+p.year}</button></p>${head('thread / No.'+p.id,p.count+' '+t('replies'))}<h1>${esc(l.title)}</h1><div class="thread-meta">Anonymous &nbsp; · &nbsp; ${p.time}</div><article class="post"><p class="post-body">${esc(l.text)}</p>${p.attachment?`<p><span class="attachment">▧ ${esc(p.attachment)} / ${t('fileUnavailable')}</span></p>`:''}</article><h2 class="reply-header">${t('selectedReplies')}</h2>${p.replies.map(reply).join('')}<p class="thread-note">${note}${t('closed')}</p></div>`}
function sidebar(active){document.getElementById('recent-list').innerHTML=posts.filter(p=>p.year===2026).slice(0,9).map(p=>`<li><button class="link" data-thread="${p.id}">${esc(localized(p).title)}</button></li>`).join('');document.getElementById('year-list').innerHTML=years.map((y,i)=>`<div class="year-row"><button data-route="archive/${y}" class="${active==='archive/'+y?'active':''}">${y}</button><span class="year-bar" style="width:${Math.round(totals[i]/481*100)}%;min-width:7px"></span><span class="year-count">${totals[i]}</span></div>`).join('');document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===active))}
function render(){updateStatic();let path=decodeURIComponent(location.hash.slice(1))||'home',entered=sessionStorage.getItem('relay-entered')==='1';gate.style.display=entered?'none':'block';board.style.display=entered?'block':'none';document.querySelectorAll('.topnav button:not([data-lang])').forEach(el=>el.disabled=!entered);if(!entered)return;if(path==='home')home();else if(path==='archive')archive();else if(/^archive\/20\d\d$/.test(path))archive(Number(path.split('/')[1]));else if(path==='rules')rules();else if(path==='about')about();else if(path.startsWith('thread/'))thread(posts.find(p=>p.id===path.split('/')[1]));else home();sidebar(path);window.scrollTo(0,0)}
document.addEventListener('click',e=>{let lang=e.target.closest('[data-lang]');if(lang){locale=lang.dataset.lang;localStorage.setItem('relay-language',locale);render();return}let enter=e.target.closest('[data-enter]');if(enter){sessionStorage.setItem('relay-entered','1');sessionStorage.setItem('relay-choice',enter.dataset.enter);localStorage.setItem('relay-visited','1');go('home');return}let p=e.target.closest('[data-thread]');if(p){go('thread/'+p.dataset.thread);return}let route=e.target.closest('[data-route]');if(route){if(sessionStorage.getItem('relay-entered')==='1')go(route.dataset.route);return}if(e.target.closest('[data-random]')&&sessionStorage.getItem('relay-entered')==='1')go('thread/'+posts[Math.floor(Math.random()*posts.length)].id)});
document.addEventListener('click',e=>{const lost=e.target.closest('[data-lost]');if(lost){const kind=lost.dataset.lost;const image=document.getElementById('lost-dialog-image');image.src=kind==='phone'?'./assets/silver-phone.webp':'./assets/sobble-keychain.webp';image.alt=t(kind==='phone'?'lostPhone':'lostKeychain');document.getElementById('lost-dialog-title').textContent=t(kind==='phone'?'lostPhone':'lostKeychain');document.getElementById('lost-dialog-note').textContent=t(kind==='phone'?'lostPhoneNote':'lostKeychainNote');document.getElementById('lost-dialog').showModal()}if(e.target.closest('[data-close-dialog]'))document.getElementById('lost-dialog').close()});
document.addEventListener('submit',e=>{if(e.target.id!=='verify-form')return;e.preventDefault();const values=new FormData(e.target);if(values.get('station')==='Leicester Square'&&values.get('exit')==='23:12'&&values.get('entry')==='23:16'){sessionStorage.setItem('relay-void-unlocked','1');render()}else document.getElementById('verify-feedback').textContent=t('verifyError')});
document.getElementById('lost-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
window.addEventListener('hashchange',render);document.getElementById('brand').addEventListener('click',e=>{if(sessionStorage.getItem('relay-entered')!=='1')e.preventDefault()});render();
