const copy = {
 zh: {
  announcementLabel:'公告 / 001',
  announcementBody:'<p>欢迎来到 relay。</p><p>relay 是一个匿名留言板。你可以在这里记录想法、提问，或讲述自己的经历。阅读无需注册。因服务器维护，帖子可能被移动、归档或删除。</p><ul><li>请勿发布任何人的真实姓名、住址或实时位置。</li><li>请勿冒充其他用户。</li><li>发帖前请先查看是否已有相关讨论。</li><li>请勿发布垃圾信息或违法内容。</li><li>请尊重其他人。</li></ul><div id="memory-warning" hidden><p>relay 不裁定什么是真的。<br>它只记得人们说过什么。</p><p><span class="memory-line">如果你的记忆与这里的记录不同，请相信你的记忆。</span></p></div>',
  understand:'[ 我已理解 ]',remember:'[ 我还记得 ]',samePlace:'两个选项通往同一处。',boardStatus:'站点状态',statusBody:'只读档案<br><span class="faint">最近同步：23:12</span>',activityTitle:'最近活动',activityBody:'23:14 · 车费调整<br>23:12 · 位置已修正<br>23:12 · 位置已修正',aboutLabel:'关于',railAbout:'留下那些在回家路上注意到的事。',railNote:'记录可能在发布后被修改。<br><br>修订历史暂不可用。',
  recent:'最近帖子',newest:'全部话题 / 按时间排序',pin:'发帖须知 / 维护公告',attachment:'文件暂不可用',reply:'回复',replies:'条回复',archiveIntro:'旧帖按当时的内容保存。部分附件与修订历史已经无法查看。',indexed:'条已收录',available:'篇可阅读',allYears:'← 所有年份',incomplete:'记录可能不完整',rulesTitle:'规则',lastRevised:'最后修订：2018/04/03',aboutTitle:'关于 relay',since:'始于 2018',backRecent:'最近帖子',selectedReplies:'回复 / 档案选录',olderReplies:'条旧回复未收录于此页。',closed:'本帖已归档，暂不接受新回复。',revised:'本回复于 {date} 修订；原文不可用。',fileUnavailable:'附件暂不可用',
  lostTitle:'失物招领',lostKeychain:'蓝色泪眼蜥钥匙扣',lostKeychainPlace:'站内拾获 · 09/23',lostPhone:'银色手机',lostPhonePlace:'Bank · Platform 3',lostKeychainNote:'钥匙圈有磨损。拾获时没有其他钥匙。',lostPhoneNote:'透明手机壳有些泛黄，背面夹着一张褪色的绿色贴纸。与 Bank 寻物帖描述相近。',
  lockedRow:'档案已锁定',lockedIntro:'此帖包含无法匹配的行程回执，暂仅显示标题。核对行程记录后可查看存档。',verify:'核对记录',verifyStation:'回执涉及的站点',verifyExit:'出站时间',verifyEntry:'进站时间',choose:'选择…',verifySubmit:'查看存档',verifyError:'记录未匹配。请核对站点和时间。',verifySuccess:'记录已匹配。以下为可读取的档案选录。',lockedBody:'有人知道回执上的 void 是什么意思吗？我是在 Leicester Square 换乘后看到的。行程里有四分钟没有站名，可客服说记录正常。',lockedReply1:'我有过一模一样的空白区间。最后显示到达，钱也照扣。',lockedReply2:'地点未匹配。记录已校正。该区间没有车站。',lockedReply3:'我记得楼主原来写过那个站名。',lockedReply4:'只要已经到达，就没有必要查中间的部分了。',lockedReply5:'这句回复昨晚还是别的内容。',lockedReply6:'该区间没有车站。',lockedReply7:'你看到 void 了吗？不要在回执上圈出来。'
 },
 en: {
  announcementLabel:'announcement / 001',
  announcementBody:'<p>welcome to relay.</p><p>relay is an anonymous bulletin board for thoughts, questions and experiences. no account is needed to read. posts may be moved, archived or deleted during server maintenance.</p><ul><li>do not share anyone’s real name, address or live location.</li><li>do not impersonate other users.</li><li>check for an existing thread before posting.</li><li>no spam or illegal content.</li><li>be respectful.</li></ul><div id="memory-warning" hidden><p>relay does not determine what is true.<br>it only remembers what was said.</p><p><span class="memory-line">if your memory differs from the record, trust your memory.</span></p></div>',
  understand:'[ I understand ]',remember:'[ I remember ]',samePlace:'both options lead to the same place.',boardStatus:'board status',statusBody:'read-only archive<br><span class="faint">last sync: 23:12</span>',activityTitle:'recent activity',activityBody:'23:14 · fare adjusted<br>23:12 · location corrected<br>23:12 · location corrected',aboutLabel:'about',railAbout:'leave what you noticed on the way home.',railNote:'records may be revised after posting.<br><br>revision history is unavailable.',
  recent:'recent threads',newest:'all topics / newest first',pin:'read before posting / maintenance notice',attachment:'file unavailable',reply:'reply',replies:'replies',archiveIntro:'Older threads are kept as submitted. Some attachments and revision histories are no longer available.',indexed:'indexed threads',available:'available here',allYears:'← all years',incomplete:'records may be incomplete',rulesTitle:'rules',lastRevised:'last revised 2018/04/03',aboutTitle:'about relay',since:'est. 2018',backRecent:'recent threads',selectedReplies:'replies / selected from archive',olderReplies:'older replies are not included in this view.',closed:'This thread is archived. New replies are closed.',revised:'This reply was revised on {date}; the earlier version is unavailable.',fileUnavailable:'file unavailable',
  lostTitle:'lost property',lostKeychain:'blue Sobble keyring',lostKeychainPlace:'found in station · 09/23',lostPhone:'silver phone',lostPhonePlace:'Bank · Platform 3',lostKeychainNote:'The ring is worn. No other keys were attached when it was found.',lostPhoneNote:'Yellowed clear case, faded green sticker tucked behind it. Similar to the phone described in the Bank thread.',
  lockedRow:'archive locked',lockedIntro:'This thread contains an unmatched journey receipt. Only the title is visible until the journey record is checked.',verify:'check journey record',verifyStation:'station on receipt',verifyExit:'exit time',verifyEntry:'entry time',choose:'choose…',verifySubmit:'view archive',verifyError:'No matching record. Check the station and times.',verifySuccess:'Record matched. Archived excerpts are now available.',lockedBody:'Does anyone know what void means on a receipt? I saw it after changing at Leicester Square. Four minutes of the journey have no station name, but support says the record is normal.',lockedReply1:'I had the exact same blank section. It still says I arrived and I was charged.',lockedReply2:'Location unmatched. Record corrected. There is no station in this section.',lockedReply3:'I remember the OP writing a station name here before.',lockedReply4:'If you arrived, you don’t need to check what happened in between.',lockedReply5:'This reply said something else last night.',lockedReply6:'There is no station in this section.',lockedReply7:'Did you see void too? Don’t circle it on the receipt.'
 }
};
const englishPosts = {
 '307812':{title:'I think I was charged twice for one journey',text:'I left Leicester Square last night, but there was another charge today for the same journey.\nHas anyone had this happen?',replies:['Check whether it’s a pending charge. Sometimes it disappears after a couple of days.','Same here. My exit is on the record, but the refund page keeps loading. Let me know if you find a way through.','But you already exited, right?','Yeah.','The time can look wrong. Sometimes syncing is delayed.','Happened to me too. If you exited in the end, you don’t need the middle of the record.','I checked mine too: exit at 23:12, entry at 23:16. The order is backwards. I still have the screenshot.','Don’t keep checking the route. You’ll only confuse yourself.','I wasn’t asking if it was okay. Why does my record include a stretch I don’t remember taking?','Support says their data is completely correct and told me not to submit it again.','You remember getting home, right? That’s enough.','Wait, Leicester Square? I’ve never heard of that station.']},
 '307899':{title:'I saw void on my receipt. What does it mean?',text:'',replies:[]},
 '307641':{title:'Anyone else unable to sleep?',text:'It’s already three. There’s a low hum outside my window.\nIt sounds like a train, but not quite. I’m probably just tired.',replies:['Could it be overnight construction?','I can hear it near my place too.']},
 '307502':{title:'Did the night bus fare go up again?',text:'Wasn’t the n55 1.75 before? Is it 2.0 now?\nEverything is getting more expensive.',replies:['Could you have tapped twice when changing?']},
 '307193':{title:'The station on the map wasn’t there yesterday',text:'I usually take the Crown line.\nThere seems to be an extra station in the middle today. Am I misremembering? Can someone check?',replies:['Which section?','The image won’t open.','I saved a screenshot. I’ll see if it’s still there tomorrow.','There’s no station there on my map.']},
 '306984':{title:'Lost my phone on the Underground',text:'I dropped a silver iPhone while changing at Bank last night. If anyone found it, please contact me.\nLast location: Platform 3.',replies:['Try lost property. Hope you get it back.']},
 '306951':{title:'Museum Garden?',text:'Does anyone know this station?\nI took a photo passing through, but now I can’t find it on the map. I think it was on the Crown line. Did I go the wrong way?',replies:['The photo says it’s corrupted. Can you upload it again?','That name sounds familiar. Was the interchange sign yellow?','The Crown line is yellow anyway.','Didn’t it used to have another name?','I can still see the attachment. Under the yellow arrow to Museum Garden it says “change for Alder line”. Can you really not open it?']},
 '306873':{title:'How do you find a friend after leaving the station at night?',text:'The exit is crowded at night. My friend is coming to meet me, but there’s barely any signal. Any tips?',replies:['Meet by the ticket machines. It’s easier than the exit.','Bring a distinctive keyring? You’ll spot them straight away.','Do not repeatedly verify the same person accompanying you.']},
 '306811':{title:'Does anyone remember the 24-hour café?',text:'The one across from the station exit. I used to get coffee there before early trains, but I can’t remember its name.',replies:['Was it the one with the green sign?']},
 '306622':{title:'Anyone want to see an exhibition this weekend?',text:'Anyone free to see the new National Gallery exhibition on Saturday afternoon?',replies:['I can make it!']},
 '306098':{title:'I think I missed my stop',text:'The same advert is outside the window. The train moved one stop, but the name hasn’t changed.\nNever mind. It’s late.',replies:['Get off and check the station name first.','Are you still there, OP?']},
 '280117':{title:'Is the old place still open?',text:'Is that tea shop near the exit still there? I want the classic jasmine milk tea.',replies:['It is. They moved across the road.']},
 '224016':{title:'My exit was recorded one minute before my entry',text:'My card says I exited at 08:52, but I didn’t enter until 08:53. Maybe it’s a time zone error.',replies:['Save a screenshot and ask support to check.']},
 '179311':{title:'Does anyone have an old route map?',text:'Looking for a copy from before last month. It wasn’t an official update; I just want to check something.',replies:['Maybe there’s one on archive.org.']},
 '135052':{title:'Did the platform announcement say my name?',text:'I probably misheard it. I had headphones on, and nobody was nearby.',replies:['It’s easy to mishear announcements when you’re tired.']},
 '103281':{title:'How long does a duplicate fare claim take?',text:'It’s been four days since I submitted mine and there’s no email. Does anyone know the usual wait?',replies:['Mine took a week.']},
 '071044':{title:'Station sign in an old photo',text:'I found a blurry interchange sign while sorting photos. Did that line change colour?',replies:['Could you post the photo?']},
 '041703':{title:'I can’t find yesterday’s thread',text:'Maybe I forgot to post it. But I remember somebody replying.',replies:['Older threads sometimes move to the archive. Try the year filter.']},
 '000009':{title:'When the record and your memory disagree',text:'Something doesn’t cease to have happened just because there’s no record.\nIf you met someone yesterday and can’t find her anywhere today, don’t rush to explain her away. Write down what you remember first.',replies:['Who are you talking about?','This reply was removed under the maintenance rules.','I remember this post saying something else yesterday.']},
 '000004':{title:'Welcome to relay',text:'Leave what you noticed here.\nPlease don’t post real names, addresses or anything that could identify someone travelling with you.',replies:['Do I really not need an account?']}
};
